-- Task 1: Opening Balance Date column
ALTER TABLE BLOOMBUDDY_FARMER_OPENING_BALANCE
ADD COLUMN OPENING_BALANCE_DATE DATE NULL AFTER OPENING_BALANCE;

ALTER TABLE BLOOMBUDDY_BUYER_OPENING_BALANCE
ADD COLUMN OPENING_BALANCE_DATE DATE NULL AFTER OPENING_BALANCE;

-- Task 2: Ledger Active flag
ALTER TABLE BLOOMBUDDY_FARMER_LEDGER
ADD COLUMN LEDGER_ACTIVE CHAR(1) NOT NULL DEFAULT 'Y' AFTER DEBIT_AMT;

ALTER TABLE BLOOMBUDDY_BUYER_LEDGER
ADD COLUMN LEDGER_ACTIVE CHAR(1) NOT NULL DEFAULT 'Y' AFTER DIS_AMT;


-- Task 2: Ledger Active flag
ALTER TABLE BLOOMBUDDY_FARMER_TRANSACTION
    ADD COLUMN PAYMENT_MODE CHAR(1) NOT NULL  AFTER DEB_AMT;

ALTER TABLE BLOOMBUDDY_BUYER_TRANSACTION
    ADD COLUMN PAYMENT_MODE CHAR(1) NOT NULL  AFTER DIS_AMT;


ALTER TABLE BLOOMBUDDY_SALES ADD COLUMN FLOWER_ID VARCHAR(20) NOT NULL AFTER debit_credit_flag;
ALTER TABLE BLOOMBUDDY_SALES ADD COLUMN BAG_COUNT INT  AFTER FLOWER_ID;


CREATE TABLE IF NOT EXISTS BLOOMBUDDY_BAG_COUNT_CONFIG (
                                                           CONFIG_ID      BIGINT       NOT NULL AUTO_INCREMENT,
                                                           CLIENT_ID      BIGINT       NOT NULL,
                                                           CLIENT_USERNAME VARCHAR(50) NOT NULL,
    FLOWER_ID      VARCHAR(60)  NOT NULL,
    FLOWER_NAME    VARCHAR(100) NOT NULL,
    SALES_DATE     DATE         NOT NULL,
    BAG_COUNT      INT          NOT NULL DEFAULT 0,
    BAG_CHECK      CHAR(1)      NOT NULL DEFAULT 'D',
    PRIMARY KEY (CONFIG_ID),
    UNIQUE KEY uk_bag_count_config (CLIENT_ID, FLOWER_ID, SALES_DATE)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


