-- Task 1: Opening Balance Date column
ALTER TABLE BLOOMBUDDY_FARMER_OPENING_BALANCE
ADD COLUMN OPENING_BALANCE_DATE DATE NULL AFTER OPENING_BALANCE;

ALTER TABLE BLOOMBUDDY_BUYER_OPENING_BALANCE
ADD COLUMN OPENING_BALANCE_DATE DATE NULL AFTER OPENING_BALANCE;

-- Task 2: Ledger Active flag
ALTER TABLE BLOOMBUDDY_FARMER_LEDGER
ADD COLUMN LEDGER_ACTIVE CHAR(1) NOT NULL DEFAULT 'Y' AFTER DEBIT_AMT;

ALTER TABLE BLOOMBUDDY_BUYER_LEDGER
ADD COLUMN LEDGER_ACTIVE CHAR(1) NOT NULL DEFAULT 'Y' AFTER DIS_AMT;
