-- Duplicate-date ledger support: allow one active (Y) row plus one inactive (N) row per party/date.
-- Run manually (no Flyway configured).

ALTER TABLE BLOOMBUDDY_BUYER_LEDGER
  DROP INDEX UQ_BUYER_LEDGER_DATE,
  ADD UNIQUE KEY UQ_BUYER_LEDGER_DATE_ACTIVE (BUYER_ID, SALES_DATE, LEDGER_ACTIVE);

ALTER TABLE BLOOMBUDDY_FARMER_LEDGER
  DROP INDEX UQ_FARMER_LEDGER_DATE,
  ADD UNIQUE KEY UQ_FARMER_LEDGER_DATE_ACTIVE (FARMER_ID, SALES_DATE, LEDGER_ACTIVE);
